# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys



class MyWindow(QMainWindow):
	def __init__(self):
		super(MyWindow, self).__init__()
		self.setGeometry(50,50,1000,500)
		self.setupUi()

	def setupUi(self):
		self.setStyleSheet("background-color: #ffbf00;")
		self.setObjectName("MainWindow")
		self.setEnabled(True)
		self.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
		self.setWindowOpacity(0.75)
		self.centralwidget = QtWidgets.QWidget(self)
		self.centralwidget.setObjectName("centralwidget")
		self.okButton = QtWidgets.QPushButton(self.centralwidget)
		self.okButton.setGeometry(QtCore.QRect(240, 330, 231, 111))
		self.okButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.okButton.setFlat(False)
		self.okButton.setObjectName("okButton")
		self.okButton.setStyleSheet("border: 5px solid black")
		self.titleLabel = QtWidgets.QLabel(self.centralwidget)
		self.titleLabel.setGeometry(QtCore.QRect(200, 120, 371, 141))
		font = QtGui.QFont()
		font.setFamily("Quicksand")
		font.setBold(True)
		font.setWeight(80)
		font.setPointSize(48)
		self.titleLabel.setFont(font)
		font.setPointSize(20)
		self.okButton.setFont(font)
		self.titleLabel.setObjectName("titleLabel")
		self.setCentralWidget(self.centralwidget)
		self.retranslateUi(self)
		QtCore.QMetaObject.connectSlotsByName(self)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle("MainWindow")
		self.okButton.setText("Okay")
		self.titleLabel.setText("Refresh time!!!")
		self.update()
		self.okButton.clicked.connect(self.closeWin)
	
	def update(self):
		self.titleLabel.adjustSize()

	def closeWin(self):
		self.close()


def createWindow():
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = MyWindow()
	ui.setWindowFlag(Qt.FramelessWindowHint)
	ui.show()
	sys.exit(app.exec_())

# createWindow()